# Generated by Django 5.2.14 on 2026-05-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=16, verbose_name="Номер кабинета"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="accounts.clinic",
                        verbose_name="Клиника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кабинет",
                "verbose_name_plural": "Кабинеты",
                "ordering": ["number"],
                "unique_together": {("clinic", "number")},
            },
        ),
        migrations.CreateModel(
            name="WeekTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                ("month", models.PositiveIntegerField(verbose_name="Месяц")),
                (
                    "week_number",
                    models.PositiveIntegerField(default=1, verbose_name="Номер недели"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_templates",
                        to="accounts.clinic",
                        verbose_name="Клиника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон недели",
                "verbose_name_plural": "Шаблоны недель",
                "ordering": ["-year", "-month", "week_number"],
            },
        ),
        migrations.CreateModel(
            name="DaySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_slots",
                        to="staff.staffmember",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_slots",
                        to="schedule.room",
                        verbose_name="Кабинет",
                    ),
                ),
                (
                    "week_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_slots",
                        to="schedule.weektemplate",
                        verbose_name="Неделя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневной слот",
                "verbose_name_plural": "Дневные слоты",
                "ordering": ["date", "room"],
            },
        ),
        migrations.CreateModel(
            name="HourSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.PositiveSmallIntegerField(verbose_name="Час")),
                (
                    "day_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hour_slots",
                        to="schedule.dayslot",
                        verbose_name="Дневной слот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Часовой слот",
                "verbose_name_plural": "Часовые слоты",
                "ordering": ["hour"],
                "unique_together": {("day_slot", "hour")},
            },
        ),
    ]
