# Generated by Django 5.2.14 on 2026-05-31 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Данные")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduler_state",
                        to="accounts.clinic",
                        verbose_name="Клиника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние планировщика",
                "verbose_name_plural": "Состояния планировщика",
            },
        ),
    ]
