# Generated by Django 5.2.14 on 2026-05-31 11:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("doctor", "Врач"),
                            ("anesthesiologist", "Анестезиолог"),
                        ],
                        max_length=32,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Цвет"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="accounts.clinic",
                        verbose_name="Клиника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Базовая ставка",
                    ),
                ),
                (
                    "elevated_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Повышенная ставка",
                    ),
                ),
                (
                    "revenue_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Порог выручки",
                    ),
                ),
                (
                    "deduct_implant",
                    models.BooleanField(
                        default=False, verbose_name="Вычитать импланты"
                    ),
                ),
                (
                    "deduct_lab",
                    models.BooleanField(
                        default=False, verbose_name="Вычитать лабораторию"
                    ),
                ),
                (
                    "staff_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_rule",
                        to="staff.staffmember",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило оплаты",
                "verbose_name_plural": "Правила оплаты",
            },
        ),
    ]
