# Generated by Django 5.0.14 on 2026-06-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffmember_macdent_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryRule',
        ),
    ]
