# Generated by Django 5.0.14 on 2026-06-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_dailyreport_closed_fields'),
        ('staff', '0002_staffmember_macdent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrevenue',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='staff.staffmember', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='payrollcalculation',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='staff.staffmember', verbose_name='Сотрудник'),
        ),
    ]
